@rootURL = http://localhost:5171

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/BookDto
Accept: application/json

###
GET {{rootURL}}/api/Book/3
Accept: application/json